# Generated by Django 4.2 on 2023-04-13 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opcoes',
            old_name='acrecimo',
            new_name='acrescimo',
        ),
    ]
